In [1]:
import numpy as np

AMF = [1, 13, 6]
NAL = [14, 1, 12]

first_matrix_2d = np.array([[1, 13, 6], [14, 1, 12]])
print(first_matrix_2d.shape)
print(first_matrix_2d.ndim)

first_matrix = first_matrix_2d

print('first_matrix')
for row in first_matrix:
    print(row)

(2, 3)
2
first_matrix
[ 1 13  6]
[14  1 12]


In [2]:
2023-4-0o147 == [2, 0, 2]
2023-4-0o147 == [1, 4, 7]

second_matrix_2d = np.array([[2, 0, 2], [1, 4, 7]])
print(second_matrix_2d.shape)
print(second_matrix_2d.ndim)

second_matrix = second_matrix_2d

print('second_matrix')
for row in second_matrix:
    print(row)

(2, 3)
2
second_matrix
[2 0 2]
[1 4 7]


In [3]:
print(first_matrix)
print(second_matrix)

[[ 1 13  6]
 [14  1 12]]
[[2 0 2]
 [1 4 7]]


In [4]:
array_first_matrix = np.array(first_matrix)
array_second_matrix = np.array(second_matrix)

third_matrix = (array_first_matrix + array_second_matrix)

print('third_matrix')
for row in third_matrix:
    print(row)

third_matrix
[ 3 13  8]
[15  5 19]


In [5]:
array_first_matrix = np.array(first_matrix)

fourth_matrix = (array_first_matrix * 2)

print('fourth_matrix')
for row in fourth_matrix:
    print(row)

fourth_matrix
[ 2 26 12]
[28  2 24]


In [6]:
second_matrix = np.array(second_matrix)
second_matrix_T = second_matrix.T

fifth_matrix = (second_matrix.T)

print('fifth_matrix')
for row in fifth_matrix:
    print(row)

fifth_matrix
[2 1]
[0 4]
[2 7]


In [7]:
third_matrix = np.array(third_matrix)
third_matrix_T = third_matrix.T

third_matrix = (third_matrix.T)

print('third_matrix')
for row in third_matrix:
    print(row)

third_matrix
[ 3 15]
[13  5]
[ 8 19]


In [8]:
array_third_matrix = np.array(third_matrix)
array_fifth_matrix = np.array(fifth_matrix)

sixth_matrix = (array_third_matrix * array_fifth_matrix)

print('sixth_matrix')
for row in sixth_matrix:
    print(row)

sixth_matrix
[ 6 15]
[ 0 20]
[ 16 133]


In [9]:
array_third_matrix = np.array(third_matrix)

sum_third_matrix = np.sum(third_matrix)

print(sum_third_matrix)

63


In [10]:
seventh_matrix = np.zeros ((2, 3))

print('seventh_matrix')
for row in seventh_matrix:
    print(row)

seventh_matrix
[0. 0. 0.]
[0. 0. 0.]
